---
- hosts: loadbalancer
  become: true
  tasks:
    - name: remove default page nginx
      become: yes
      file:
        state: absent
        path: "/etc/nginx/sites-enabled"
    - name: inject lb.conf file for nginx
      become: yes
      copy:
        src: loadbalancer.conf
        dest: /etc/nginx/conf.d/loadbalancer.conf
        owner: root
        group: root
        mode: 0644
    - name: nginx service state
      become: yes
      service:
         name: nginx
         state: restarted
